---
  - include_tasks: ubuntu-install.yml
    when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

  - include_tasks: centos-install.yml
    when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'

  - name: configure kibana
    template:
      src: kibana.yml.j2
      dest: /etc/kibana/kibana.yml
      owner: root
      group: kibana
    notify: restart kibana
