---
  - name: check cluster mode variable
    fail:
      msg: "FAILED: Invalid Cluster Mode {{ cluster_mode }}"
    when: cluster_mode != "on" and cluster_mode != "off"

  - name: check cluster mode variable
    fail:
      msg: "FAILED: Invalid Cluster Count"
    when: cluster_mode == "on" and groups['elasticsearch']|length<2

  - include_tasks: ubuntu-install.yml
    when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

  - include_tasks: centos-install.yml
    when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'

  - name: Add IP address of all hosts to all hosts
    lineinfile:
      dest: /etc/hosts
      regexp: '.*{{ item }}$'
      line: "{{ hostvars[item].ansible_host }} {{ hostvars[item].host_name }}"
      state: present
    when: hostvars[item].ansible_host is defined
    with_items: "{{ groups.elasticsearch }}"

  - name: configure elasticsearch
    template:
      src: elasticsearch.yml.j2
      dest: /etc/elasticsearch/elasticsearch.yml
      owner: root
      group: elasticsearch
    notify: restart elasticsearch

  - name: configure nginx
    template:
      src: default.conf.j2
      dest: /etc/nginx/conf.d/default.conf
      owner: root
      group: root
    when: cluster_mode == "on"
    notify: restart nginx
