---
  - name: import elasticsearch PGP key
    apt_key:
      url: https://artifacts.elastic.co/GPG-KEY-elasticsearch
      state: present

  - name: enable elasticsearch repository
    apt_repository:
      repo: deb https://artifacts.elastic.co/packages/7.x/apt stable main
      state: present

  - name: install packages
    apt:
      name: [
        "kibana",
        "default-jdk"
        ]
      state: latest
